### ISSUE TITLE
Reestructuración de la clase "Empresa" en la implementación.

### ISSUE THREAD

**Issue by mariamartinmarin** [IngenieriaWebUCA/iw2016-tempojobs#14]
Actualmente la clase "Empresa" sirve para modelar los usuarios de las empresas. Esto hace que sea requisito indispensable que sólo pueda haber un usuario por empresa. De esta manera, se decide crear una nueva clase "Usuario" que se relacione con "Empresa" de manera que podamos tener más de un usuario por empresa.

**Comment by MatiasDiAg** [comment]
Creada nueva entidad UsuarioEmpresa que hereda de la interfaz AbstractUsuario y tiene relación 1:N con la entidad Empresa.
